name: Build and Deploy
on: 
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          find . -maxdepth 1 -type f -exec rm -f {} +
          find . -mindepth 1 ! -regex '^./dist\(/.*\)?|^./.git\(/.*\)?' -delete
          cp -a ./dist/* .
          rm -rf dist
          ls -la

      - name: Commit Files
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "Double-Dev"
          git add .
          git commit -m "Build from production." -a
      
      - name: Push Files 🚀
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          force: true
          
